### ISSUE TITLE
Standalone Santa

### ISSUE THREAD

**Issue by mlw** [northpolesec/santa#132]
It should be possible for a standalone user or other certain users to self approve binaries if they authenticate with TouchID. 

This will make using lockdown mode far easier for a standalone user and help improve developer workflows. 

## Tasks

 - [x] Implement standalone mode (see PR #86)
 - [X] Update the sync protocol to include a new audit event and clean sync type for rules generated in standalone mode
 - [ ] Update Santa to send an audit event when a new rule is created by a user in standalone mode (this can be queued by the sync manager.)
 - [ ] Add documentation: 
   - [ ]  Explaining the mode and when the approve button shows up
   - [ ]  Fix up the sync docs
 - [ ] Add a rule browser 
 - [ ] Make santactl require touch ID when password fallback is disabled.

## Related PRs
 - #86
